#!/usr/bin/env perl

use 5.10.0;
use strict;
use autodie;
use warnings;

# custom search paths
BEGIN {
    use File::Basename;
    use Cwd qw/abs_path/;

    my $alf = dirname abs_path $0;
    push @INC,
        $alf.'/lib',
        $alf.'/tasks',
        $alf.'/local/lib/perl5';
}

use Try::Tiny;

use Alfred::Cli;
use Alfred::Dispatcher;


my $order      = Alfred::Cli::get_order();
my $task       = Alfred::Cli::get_task();
my $dispatcher = Alfred::Dispatcher->new();

$order = 'help' unless $order and $order ne 'new';

try   { $dispatcher->$order($task) }
catch { die("$_\n\n") }
